"""
Synthetic test data generators.

IMPORTANT: Never copy or use production personal data in tests or analytics.
All test users and orders MUST be generated by these functions.
"""
try:
    from faker import Faker
except ImportError:
    raise ImportError("Install faker: pip install faker")

_fake = Faker()


def generate_test_user() -> dict:
    return {
        "username": _fake.user_name(),
        "password": "Test@12345!",
        "phone_number": _fake.numerify("+1##########"),
        "first_name": _fake.first_name(),
        "last_name": _fake.last_name(),
        "consent_to_data_processing": True,
    }


def generate_test_order(user_id: int, menu_item_id: int) -> dict:
    return {
        "user_id": user_id,
        "delivery_address": _fake.address().replace("\n", ", ")[:200],
        "phone_number": _fake.numerify("+1##########"),
        "items": [{"menu_item_id": menu_item_id, "quantity": 1}],
    }
